#site specific settings
site:
  ip: 192.168.33.10 # virtual machine ip address
  sitename: sitename.test # virtual machine domain eg http://sitename.test
  database: sitename # create default database
  mysqlpassword: password # mysql root password
  virtualmemory: 2048 # virtual machine memory